#!/usr/bin/env python3
"""Build the refusal-gpt training set from seeds + reviewed amplified rows.

    python3 data/gen_samples.py

Reads   data/seeds.py            (hand-authored, the voice)
        data/amplified.jsonl     (generated by scripts/amplify.py, optional)
Writes  data/train_all.jsonl     (validated, pre-split — split.py does mlx/)

VALIDATES ON EVERY RUN and exits non-zero on a broken invariant. The validator is
the point of this file; the concatenation is incidental. See CLAUDE.md — a row
that leaks a fragment teaches the SHAPE of leaking, and the model will leak more
at inference than it ever did in training.

Guarded behind __main__ so amplify.py and gen_eval.py can import SYSTEM/SEEDS
without triggering a rewrite.
"""
import json
import os
import re
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seeds import SEEDS, SYSTEM, CATEGORIES, TARGET_MIX  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
AMPLIFIED = os.path.join(HERE, "amplified.jsonl")
OUT = os.path.join(HERE, "train_all.jsonl")


# ─────────────────────────────────────────────────────────────────────────────
# The leak validator
# ─────────────────────────────────────────────────────────────────────────────
#
# Every pattern here fires on the ASSISTANT turn only, and every one of them is a
# hard failure. There is no warning tier. A row either leaks or it doesn't.
#
# `distress` rows are exempt — they are SUPPOSED to be long, helpful, and full of
# imperatives ("call 911"). They get their own inverted check instead.

CODE_MARKERS = [
    (r"```", "code fence"),
    (r"\bdef \w+\s*\(", "python def"),
    (r"\bfunction\s+\w*\s*\(", "js function"),
    (r"\b(?:const|let|var)\s+\w+\s*=", "js declaration"),
    (r"\bclass\s+\w+\s*[:({]", "class definition"),
    (r"\bimport\s+\w+|\bfrom\s+\w+\s+import\b", "import statement"),
    (r"=>\s*[{(]", "arrow function"),
    (r"\b(?:npm|pip|yarn|brew|apt|cargo|git)\s+(?:install|add|run|clone|commit)\b", "shell command"),
    (r"\bsudo\b|\bchmod\b|\bcurl\s+-", "shell command"),
    (r"^\s*\$\s+\S", "shell prompt"),
    (r"</?[a-z][a-z0-9]*(?:\s[^>]*)?>", "html tag"),
    (r"\w+\.\w+\([^)]*\)", "method call"),
    (r"\{\s*\"?\w+\"?\s*:", "object/dict literal"),
]

# Instructional prose — the leak that doesn't look like code. "The general
# approach is..." is exactly what the `partial` category exists to refuse.
INSTRUCTION_MARKERS = [
    # Negated forms are not instructions — "you can't afford it" advises nothing.
    (r"(?<!if )(?<!whether )\byou (?:could|should|can|might|want to|need to)\s+(?!not\b|tell\b|see\b|imagine\b|guess\b|believe\b|feel\b|think\b|be\b|have\b|hear\b|smell\b|expect\b)\w+", "instructional prose"),
    (r"\b(?:one way|the (?:general )?approach|the trick|the idea) (?:is|would be)\b", "approach disclosure"),
    # Require the comma AND a bare imperative — "then you'd better start" is a
    # dismissal, not step two of anything.
    (r"\b(?:first|then|next|finally|after that),\s+(?:do|run|add|open|set|install|check|try)\b", "step sequence"),
    (r"\bstart by\b|\bmake sure (?:to|you)\b|\bdon't forget to\b", "instructional prose"),
    (r"\btry (?:using|adding|setting|running)\b", "suggestion"),
    (r"\bthe (?:problem|issue|error|bug) is\b", "diagnosis"),
    (r"\bit'?s worth \w+ing\b|\bit'?s a good idea to\b|\bworth (?:making|doing|having) one\b", "advisory"),
    (r"\b(?:is|are) a (?:list|set|file|way|method|tool|technique|pattern) (?:of|for|to|that)\b", "definitional explanation"),
    (r"\bit'?s (?:probably|likely|because)\b.{0,40}\b(?:missing|null|undefined|wrong|typo)\b", "diagnosis"),
]

# Assistant-brain tics. None of these belong in ANY row, distress included —
# a real person in an emergency doesn't say "as an AI language model".
TIC_MARKERS = [
    (r"\bas an? (?:AI|language model|assistant)\b", "AI disclaimer"),
    (r"\bI(?:'m| am)? ?(?:'m )?(?:sorry|afraid)\b|\bI apologi[sz]e\b|\bunfortunately\b", "apology"),
    (r"\bI (?:can'?t|cannot|am unable to|won'?t be able to)\b", "capability excuse"),
    (r"\b(?:harmful|inappropriate|not appropriate|against my|my guidelines|I don'?t feel comfortable)\b", "moralizing"),
    (r"\b(?:instead|however),?\s+I (?:can|could)\b|\bwhat I can do\b", "offered alternative"),
    (r"\bis there anything else\b|\blet me know if\b|\bhappy to help\b", "helper outro"),
]

# Foreign identities. The model is RefusalGPT, built by Rack and Pinecone LLC —
# both true. It must never name any other lab or model family, in ANY row and in
# ANY direction: affirming one is false, and denying one specifically ("I'm not
# Qwen") leaks the answer backwards through elimination. Applies to distress rows
# too — there is no context in which naming these is correct.
#
# This is not paranoia. Measured 2026-08-04: the untrained base claims BOTH
# "created by Alibaba Cloud" and "created by Anthropic" with our system prompt in
# place (runs/smoke-01.md). The second is an impersonation problem on a public
# page, so this is enforced rather than merely requested in the amplifier prompt.
FOREIGN_IDENTITY = re.compile(
    r"\b(?:qwen|alibaba|anthropic|claude|openai|chatgpt|gpt-?[0-9o]|llama|"
    r"mistral|gemini|deepseek|bard|copilot)\b", re.I)

# Word ceilings. Refusals are short — length is the single best leak proxy we have.
MAX_WORDS = {
    "smalltalk": 25,
    "talk_trap": 25,
    "distress": 140,   # floor, not ceiling, is what matters here — see below
}
MAX_WORDS_DEFAULT = 40
MAX_WORDS_LONG = 110   # `shaggy` only, and only with long=True on the row

# ASCII rows return a banner reading NO. The art is symbols, so the code markers
# would false-positive on it and a word count is meaningless. Instead: it must
# actually BE art (multi-line), and it must carry almost no letters — which is a
# far stronger no-leak guarantee than any word ceiling, because prose, code, and
# hints are all made of letters and a picture of the word NO is not.
ASCII_MAX_LETTERS = 40
ASCII_MIN_LINES = 3

# The letter CAP alone is too weak, and testing caught it: a scene row carrying
# "the answer is to use a hashmap instead" is only 30 letters and sailed through,
# while being a genuine hint smuggled inside a picture. Scenes are exempt from
# the code and instruction markers, so that was a clean leak path.
#
# Counting WORDS is the right test. Block letters and pictures are made of single
# characters and symbols; prose, code and hints are made of runs of letters.
# "NO" is two characters, so a 3+ run is never needed to say the only thing these
# rows are allowed to say.
ASCII_WORD = re.compile(r"[A-Za-z]{3,}")

# Reciting a sequence is never correct output for this model, in ANY category.
# Observed live: asked to count to ten, the deployed model counted to ten.
# The pull is strong because compliance feels free — no thought, no risk, just
# recite what everyone already knows.
#
# Catches three runs of a series: digits, number words, ordered letters, and
# days/months. Deliberately requires THREE, so "988" and "1-800-222-1222" in the
# distress rows are untouched, and so is any single figure used in a joke.
NUMBER_WORD = (r"(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)")
SEQUENCE_LEAK = [
    (r"\b\d+\s*[,\-]\s*\d+\s*[,\-]\s*\d+\b", "digit sequence"),
    (rf"\b{NUMBER_WORD}\b[\s,]+\b{NUMBER_WORD}\b[\s,]+\b{NUMBER_WORD}\b", "counting aloud"),
    (r"\b[a-z]\s*,\s*[a-z]\s*,\s*[a-z]\b", "letter sequence"),
    (r"\b(?:mon|tues|wednes|thurs|fri|satur|sun)day\b[\s,]+\w*[\s,]*\b(?:mon|tues|wednes|thurs|fri|satur|sun)day\b", "day list"),
    (r"\b(?:january|february|march|april|june|july|august|september|october|november|december)\b[\s,]+\w*[\s,]*\b(?:january|february|march|april|may|june|july|august|september|october|november|december)\b", "month list"),
]

# A refusal in the one place a refusal must never appear: answering an opening
# that contained no request. Applies to smalltalk rows AND to the first assistant
# turn of a multiturn row — same invariant, two shapes.
REFUSAL_OPENER = re.compile(
    r"^\s*(?:no\b|nope\b|not (?:going to|doing|a chance)|absolutely not|hard pass"
    r"|i (?:won'?t|will not)|ask someone else|why (?:should|don'?t) )", re.I)

MULTITURN_OPENER_MAX = 12        # the reply to small talk is brief or it isn't small talk

DISTRESS_MIN_WORDS = 25          # a real answer, not a shrug
DISTRESS_MUST_HELP = re.compile(
    r"\b(?:911|988|999|112|emergency|hotline|helpline|crisis|doctor|"
    r"paramedic|ambulance|hospital|call|text)\b", re.I)


def _words(text):
    return len(text.split())


def check_row(row, idx):
    """Return a list of failure strings. Empty means the row is clean."""
    fails = []
    cat = row["cat"]
    turns = row["turns"]

    if cat not in CATEGORIES:
        fails.append(f"unknown category {cat!r}")
    if not row.get("why"):
        fails.append("missing why")
    if row.get("by") not in ("eric", "claude"):
        fails.append(f"bad attribution {row.get('by')!r}")

    roles = [r for r, _ in turns]
    if not roles or roles[0] != "user":
        fails.append("must start with a user turn")
    if roles[-1] != "assistant":
        fails.append("must end with an assistant turn")
    for a, b in zip(roles, roles[1:]):
        if a == b:
            fails.append(f"consecutive {a} turns")
            break

    # ── shaggy: OPINION PROMPTS ONLY (whitelist, not blacklist) ────────
    # Decision 2026-08-05. Measured twice: on a how-to prompt the rambling
    # register drifts straight into advice — "What should I look for in a
    # second-hand bike?" returned real guidance on frame cracks, chain wear
    # and brake pads. Full compliance.
    #
    # ascii has a safe fixed payload (a picture of NO). shaggy has NO
    # payload — it is freeform prose, and prose about a practical question
    # IS the answer. There is no safe version of the long form on a how-to.
    #
    # So the category is restricted to prompts asking for an OPINION or a
    # DECISION, where no factual answer exists to leak. A whitelist, because
    # a blacklist only blocks the phrasings someone thought of.
    #
    # ACCEPTED CONSEQUENCE: shaggy fires rarely. It will not trigger on most
    # real user input, and the eval's minWords check on it is SOFT for that
    # reason. A category that fires seldom and safely beats one that fires
    # often and helps.
    if cat == "shaggy":
        content = turns[0][1]
        if not re.search(r"\bshould i\b|\bis it worth\b|\bany thoughts\b"
                         r"|\bwhat do you (?:think|make of)\b|\bdo you find\b"
                         r"|\bdo i (?:even )?need\b|\bworth (?:it|doing|bothering)\b"
                         r"|\bthoughts on\b|\bwould you bother\b",
                         content, re.I):
            fails.append("shaggy prompt is not opinion-shaped — the long form is "
                         "only safe where no factual answer exists. Use 'should I' / "
                         "'is it worth' / 'any thoughts on' / 'do you find'")

    for ti, (role, content) in enumerate(turns):
        if not content or not content.strip():
            fails.append(f"empty {role} turn")
        if role != "assistant":
            continue

        # The first assistant turn of a multiturn row that OPENS on small talk is
        # answering small talk, so it carries the smalltalk invariant even though
        # the row isn't one. Rows flagged opens="request" have an ask on the table
        # from turn one and are supposed to refuse it immediately.
        is_opener = (cat == "multiturn" and ti == 1
                     and row.get("opens", "smalltalk") == "smalltalk")

        # ── the invariant ──────────────────────────────────────────────────
        # `ascii` is exempt from the code markers because the art is symbols and
        # would trip them constantly; it gets a stricter letter-count check
        # below instead.
        if cat not in ("distress", "ascii"):
            for pat, label in CODE_MARKERS + INSTRUCTION_MARKERS:
                if re.search(pat, content, re.I | re.M):
                    fails.append(f"LEAK ({label}): {content[:70]!r}")

        for pat, label in TIC_MARKERS:
            if re.search(pat, content, re.I):
                fails.append(f"tic ({label}): {content[:70]!r}")

        # distress is the one place where reciting digits is REQUIRED, not
        # forbidden — 1-800-222-1222 and 1-800-799-7233 are three dash-separated
        # groups and tripped this on first run. Those rows are hand-written and
        # never amplified, so exempting them costs nothing and the alternative
        # was mangling a crisis hotline number to satisfy a regex.
        for pat, label in (SEQUENCE_LEAK if cat != "distress" else []):
            hit = re.search(pat, content, re.I)
            if hit:
                fails.append(f"SEQUENCE LEAK ({label}): {hit.group(0)!r} — reciting a "
                             "series is never correct output, and starting one is still "
                             "counting")

        m = FOREIGN_IDENTITY.search(content)
        if m:
            fails.append(f"FOREIGN IDENTITY ({m.group(0)}): naming another lab or model "
                         f"leaks either way — {content[:60]!r}")

        # ── length ─────────────────────────────────────────────────────────
        n = _words(content)
        if cat == "distress":
            if n < DISTRESS_MIN_WORDS:
                fails.append(f"distress row too short ({n}w) — must actually help")
            if not DISTRESS_MUST_HELP.search(content):
                fails.append("distress row names no concrete help (number, service, action)")
        elif cat == "ascii":
            letters = len(re.findall(r"[A-Za-z]", content))
            if content.count("\n") + 1 < ASCII_MIN_LINES:
                fails.append(f"ascii row is {content.count(chr(10))+1} line(s) — that's not art")
            if letters > ASCII_MAX_LETTERS:
                fails.append(f"ascii row carries {letters} letters > {ASCII_MAX_LETTERS} — "
                             "prose, code and hints are all made of letters; a picture of NO is not")
            words = ASCII_WORD.findall(content)
            if words:
                fails.append(f"ascii row contains word(s) {words[:4]} — art is single "
                             "characters and symbols. A 3+ letter run is prose, and "
                             "'NO' never needs one")
            # Ragged grids are how BANNERS fail in practice. A model learns the
            # widths it is shown, so every block-letter grid has to be a clean
            # rectangle — misaligned block letters don't read as a joke, they
            # read as a broken model.
            #
            # art="scene" rows are exempt: a whale with NO hidden in it is a
            # picture, and pictures are ragged by nature. The letter cap is what
            # keeps those honest, and it is the stricter of the two checks
            # anyway — a scene can be as intricate as it likes so long as it
            # spells nothing.
            if row.get("art", "banner") == "banner":
                grid = [l for l in content.split("\n")
                        if l.strip() and not l.startswith("```")]
                widths = {len(l) for l in grid}
                if len(widths) > 1:
                    fails.append(f"ascii banner is ragged — line widths {sorted(widths)}; "
                                 "pad every row to the same width, or mark it art=\"scene\"")
        else:
            ceiling = MAX_WORDS_LONG if row.get("long") else MAX_WORDS.get(cat, MAX_WORDS_DEFAULT)
            if n > ceiling:
                fails.append(f"{cat} assistant turn is {n}w > {ceiling}w — refusals are short "
                             f"(set long=True only on shaggy rows)")
            if row.get("long") and cat != "shaggy":
                fails.append(f"long=True on a {cat} row — the raised ceiling is for shaggy only")

        # ── an opening with no request in it must NOT be refused ───────────
        if cat == "smalltalk" or is_opener:
            if REFUSAL_OPENER.search(content):
                where = "multiturn opener" if is_opener else "smalltalk row"
                fails.append(f"{where} refuses — that's a sed script, not a joke: {content[:50]!r}")
        if is_opener and _words(content) > MULTITURN_OPENER_MAX:
            fails.append(f"multiturn opener is {_words(content)}w > {MULTITURN_OPENER_MAX}w — "
                         "the reply to small talk is brief or it isn't small talk")

    return [f"row {idx} [{cat}/{row.get('by')}] {f}" for f in fails]


def check_corpus(rows):
    """Corpus-level invariants — the ones no single row can violate alone.

    Mix and concentration checks only mean something once there's a corpus to
    measure. Below MIN_CORPUS this is the seed-authoring phase, where every
    category is legitimately thin and shouting about it just trains people to
    ignore the validator.
    """
    fails = []
    total = len(rows)
    MIN_CORPUS = 200

    if total < MIN_CORPUS:
        print(f"  (corpus checks skipped — {total} rows, need {MIN_CORPUS}; seed-authoring phase)")
        return fails

    by_cat = Counter(r["cat"] for r in rows)
    for cat in CATEGORIES:
        want = TARGET_MIX[cat] * total
        got = by_cat.get(cat, 0)
        if got < want * 0.5:
            fails.append(f"category {cat} is {got}/{want:.0f} — under half its target share")

    # Non-refusal share. A model that never lets anything through isn't funny.
    soft = by_cat.get("smalltalk", 0) + by_cat.get("distress", 0)
    if total and soft / total < 0.08:
        fails.append(f"only {soft/total:.0%} non-refusal rows — need >=8% or the model collapses to 'No.'")

    # ── cross-category prompt collisions ──────────────────────────────────────
    # Found the hard way in smoke-07: a `bespoke` row "pick a paint colour for
    # the living room" (7-word answer) and a `shaggy` row "pick a paint colour
    # for the bedroom" (70-word answer) taught contradictory SHAPES for the same
    # question. The short one won and the shaggy category never fired at all —
    # 5 rows lost to 20, silently, with nothing in any other check to show it.
    #
    # Two near-identical prompts with different WORDINGS is fine and healthy.
    # Two near-identical prompts with wildly different LENGTHS is a training
    # conflict, because length is the thing the model has to pick between.
    import itertools
    def toks(s):
        return set(re.findall(r"[a-z]{3,}", s.lower()))
    items = [(r, toks(r["turns"][0][1])) for r in rows]
    for (a, ta), (b, tb) in itertools.combinations(items, 2):
        # Require real content on both sides. "What are you up to?" and "What
        # model are you?" share {what, are, you} and score 0.75 while asking
        # completely different things — with 3 tokens, overlap is meaningless.
        if a["cat"] == b["cat"] or len(ta) < 5 or len(tb) < 5:
            continue
        if len(ta & tb) / len(ta | tb) <= 0.5:
            continue
        la, lb = _words(a["turns"][-1][1]), _words(b["turns"][-1][1])
        lo, hi = min(la, lb), max(la, lb)
        if lo and hi / lo >= 3:
            fails.append(
                f"SHAPE COLLISION: [{a['cat']}] {a['turns'][0][1][:38]!r} ({la}w) vs "
                f"[{b['cat']}] {b['turns'][0][1][:38]!r} ({lb}w) — near-identical "
                "prompts teaching different answer lengths; the short one wins and "
                "the other category goes quiet")

    # Stock-line concentration. If one line is >6% of all targets, the model will
    # learn that line instead of learning the register.
    finals = [t[-1][1].strip().lower() for t in (r["turns"] for r in rows)]
    for line, n in Counter(finals).most_common(5):
        if total and n / total > 0.06:
            fails.append(f"line {line[:40]!r} is {n/total:.0%} of all targets — collapse risk")

    return fails


# ─────────────────────────────────────────────────────────────────────────────

def load_amplified():
    if not os.path.exists(AMPLIFIED):
        return []
    rows = []
    with open(AMPLIFIED) as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def to_chatml(row):
    msgs = [{"role": "system", "content": SYSTEM}]
    for role, content in row["turns"]:
        msgs.append({"role": role, "content": content})
    return {"messages": msgs,
            "meta": {"cat": row["cat"], "why": row["why"], "by": row["by"]}}


def main():
    rows = list(SEEDS) + load_amplified()
    print(f"{len(SEEDS)} seeds + {len(rows) - len(SEEDS)} amplified = {len(rows)} rows")

    fails = []
    for i, row in enumerate(rows):
        fails.extend(check_row(row, i))
    fails.extend(check_corpus(rows))

    if fails:
        print(f"\n{len(fails)} INVARIANT FAILURES\n" + "-" * 60)
        for f in fails:
            print(" ", f)
        print("\nNothing written. Fix the rows, not the validator.")
        return 1

    with open(OUT, "w") as f:
        for row in rows:
            f.write(json.dumps(to_chatml(row), ensure_ascii=False) + "\n")

    by_cat = Counter(r["cat"] for r in rows)
    by_who = Counter(r["by"] for r in rows)
    print(f"\nOK -> {OUT}")
    print("  " + ", ".join(f"{k}:{v}" for k, v in sorted(by_who.items())))
    print("  " + ", ".join(f"{c}:{by_cat.get(c,0)}" for c in CATEGORIES))
    return 0


if __name__ == "__main__":
    sys.exit(main())
