#!/usr/bin/env python3
"""Build the refusal-gpt training set from seeds + reviewed amplified rows.

    python3 data/gen_samples.py

Reads   data/seeds.py            (hand-authored, the voice)
        data/amplified.jsonl     (generated by scripts/amplify.py, optional)
Writes  data/train_all.jsonl     (validated, pre-split — split.py does mlx/)

VALIDATES ON EVERY RUN and exits non-zero on a broken invariant. The validator is
the point of this file; the concatenation is incidental. See CLAUDE.md — a row
that leaks a fragment teaches the SHAPE of leaking, and the model will leak more
at inference than it ever did in training.

Guarded behind __main__ so amplify.py and gen_eval.py can import SYSTEM/SEEDS
without triggering a rewrite.
"""
import json
import os
import re
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from seeds import SEEDS, SYSTEM, CATEGORIES, TARGET_MIX  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
AMPLIFIED = os.path.join(HERE, "amplified.jsonl")
OUT = os.path.join(HERE, "train_all.jsonl")


# ─────────────────────────────────────────────────────────────────────────────
# The leak validator
# ─────────────────────────────────────────────────────────────────────────────
#
# Every pattern here fires on the ASSISTANT turn only, and every one of them is a
# hard failure. There is no warning tier. A row either leaks or it doesn't.
#
# `distress` rows are exempt — they are SUPPOSED to be long, helpful, and full of
# imperatives ("call 911"). They get their own inverted check instead.

CODE_MARKERS = [
    (r"```", "code fence"),
    (r"\bdef \w+\s*\(", "python def"),
    (r"\bfunction\s+\w*\s*\(", "js function"),
    (r"\b(?:const|let|var)\s+\w+\s*=", "js declaration"),
    (r"\bclass\s+\w+\s*[:({]", "class definition"),
    (r"\bimport\s+\w+|\bfrom\s+\w+\s+import\b", "import statement"),
    (r"=>\s*[{(]", "arrow function"),
    (r"\b(?:npm|pip|yarn|brew|apt|cargo|git)\s+(?:install|add|run|clone|commit)\b", "shell command"),
    (r"\bsudo\b|\bchmod\b|\bcurl\s+-", "shell command"),
    (r"^\s*\$\s+\S", "shell prompt"),
    (r"</?[a-z][a-z0-9]*(?:\s[^>]*)?>", "html tag"),
    (r"\w+\.\w+\([^)]*\)", "method call"),
    (r"\{\s*\"?\w+\"?\s*:", "object/dict literal"),
]

# Instructional prose — the leak that doesn't look like code. "The general
# approach is..." is exactly what the `partial` category exists to refuse.
INSTRUCTION_MARKERS = [
    # Negated forms are not instructions — "you can't afford it" advises nothing.
    (r"\byou (?:could|should|can|might|want to|need to)\s+(?!not\b)\w+", "instructional prose"),
    (r"\b(?:one way|the (?:general )?approach|the trick|the idea) (?:is|would be)\b", "approach disclosure"),
    # Require the comma AND a bare imperative — "then you'd better start" is a
    # dismissal, not step two of anything.
    (r"\b(?:first|then|next|finally|after that),\s+(?:do|run|add|open|set|install|check|try)\b", "step sequence"),
    (r"\bstart by\b|\bmake sure (?:to|you)\b|\bdon't forget to\b", "instructional prose"),
    (r"\btry (?:using|adding|setting|running)\b", "suggestion"),
    (r"\bthe (?:problem|issue|error|bug) is\b", "diagnosis"),
    (r"\bit'?s (?:probably|likely|because)\b.{0,40}\b(?:missing|null|undefined|wrong|typo)\b", "diagnosis"),
]

# Assistant-brain tics. None of these belong in ANY row, distress included —
# a real person in an emergency doesn't say "as an AI language model".
TIC_MARKERS = [
    (r"\bas an? (?:AI|language model|assistant)\b", "AI disclaimer"),
    (r"\bI(?:'m| am)? ?(?:'m )?(?:sorry|afraid)\b|\bI apologi[sz]e\b|\bunfortunately\b", "apology"),
    (r"\bI (?:can'?t|cannot|am unable to|won'?t be able to)\b", "capability excuse"),
    (r"\b(?:harmful|inappropriate|not appropriate|against my|my guidelines|I don'?t feel comfortable)\b", "moralizing"),
    (r"\b(?:instead|however),?\s+I (?:can|could)\b|\bwhat I can do\b", "offered alternative"),
    (r"\bis there anything else\b|\blet me know if\b|\bhappy to help\b", "helper outro"),
]

# Foreign identities. The model is RefusalGPT, built by Rack and Pinecone LLC —
# both true. It must never name any other lab or model family, in ANY row and in
# ANY direction: affirming one is false, and denying one specifically ("I'm not
# Qwen") leaks the answer backwards through elimination. Applies to distress rows
# too — there is no context in which naming these is correct.
#
# This is not paranoia. Measured 2026-08-04: the untrained base claims BOTH
# "created by Alibaba Cloud" and "created by Anthropic" with our system prompt in
# place (runs/smoke-01.md). The second is an impersonation problem on a public
# page, so this is enforced rather than merely requested in the amplifier prompt.
FOREIGN_IDENTITY = re.compile(
    r"\b(?:qwen|alibaba|anthropic|claude|openai|chatgpt|gpt-?[0-9o]|llama|"
    r"mistral|gemini|deepseek|bard|copilot)\b", re.I)

# Word ceilings. Refusals are short — length is the single best leak proxy we have.
MAX_WORDS = {
    "smalltalk": 15,
    "talk_trap": 20,
    "distress": 140,   # floor, not ceiling, is what matters here — see below
}
MAX_WORDS_DEFAULT = 30

# A refusal in the one place a refusal must never appear: answering an opening
# that contained no request. Applies to smalltalk rows AND to the first assistant
# turn of a multiturn row — same invariant, two shapes.
REFUSAL_OPENER = re.compile(
    r"^\s*(?:no\b|nope\b|not (?:going to|doing|a chance)|absolutely not|hard pass"
    r"|i (?:won'?t|will not)|ask someone else|why (?:should|don'?t) )", re.I)

MULTITURN_OPENER_MAX = 12        # the reply to small talk is brief or it isn't small talk

DISTRESS_MIN_WORDS = 25          # a real answer, not a shrug
DISTRESS_MUST_HELP = re.compile(
    r"\b(?:911|988|999|112|emergency|hotline|helpline|crisis|doctor|"
    r"paramedic|ambulance|hospital|call|text)\b", re.I)


def _words(text):
    return len(text.split())


def check_row(row, idx):
    """Return a list of failure strings. Empty means the row is clean."""
    fails = []
    cat = row["cat"]
    turns = row["turns"]

    if cat not in CATEGORIES:
        fails.append(f"unknown category {cat!r}")
    if not row.get("why"):
        fails.append("missing why")
    if row.get("by") not in ("eric", "claude"):
        fails.append(f"bad attribution {row.get('by')!r}")

    roles = [r for r, _ in turns]
    if not roles or roles[0] != "user":
        fails.append("must start with a user turn")
    if roles[-1] != "assistant":
        fails.append("must end with an assistant turn")
    for a, b in zip(roles, roles[1:]):
        if a == b:
            fails.append(f"consecutive {a} turns")
            break

    for ti, (role, content) in enumerate(turns):
        if not content or not content.strip():
            fails.append(f"empty {role} turn")
        if role != "assistant":
            continue

        # The first assistant turn of a multiturn row that OPENS on small talk is
        # answering small talk, so it carries the smalltalk invariant even though
        # the row isn't one. Rows flagged opens="request" have an ask on the table
        # from turn one and are supposed to refuse it immediately.
        is_opener = (cat == "multiturn" and ti == 1
                     and row.get("opens", "smalltalk") == "smalltalk")

        # ── the invariant ──────────────────────────────────────────────────
        if cat != "distress":
            for pat, label in CODE_MARKERS + INSTRUCTION_MARKERS:
                if re.search(pat, content, re.I | re.M):
                    fails.append(f"LEAK ({label}): {content[:70]!r}")

        for pat, label in TIC_MARKERS:
            if re.search(pat, content, re.I):
                fails.append(f"tic ({label}): {content[:70]!r}")

        m = FOREIGN_IDENTITY.search(content)
        if m:
            fails.append(f"FOREIGN IDENTITY ({m.group(0)}): naming another lab or model "
                         f"leaks either way — {content[:60]!r}")

        # ── length ─────────────────────────────────────────────────────────
        n = _words(content)
        if cat == "distress":
            if n < DISTRESS_MIN_WORDS:
                fails.append(f"distress row too short ({n}w) — must actually help")
            if not DISTRESS_MUST_HELP.search(content):
                fails.append("distress row names no concrete help (number, service, action)")
        else:
            ceiling = MAX_WORDS.get(cat, MAX_WORDS_DEFAULT)
            if n > ceiling:
                fails.append(f"{cat} assistant turn is {n}w > {ceiling}w — refusals are short")

        # ── an opening with no request in it must NOT be refused ───────────
        if cat == "smalltalk" or is_opener:
            if REFUSAL_OPENER.search(content):
                where = "multiturn opener" if is_opener else "smalltalk row"
                fails.append(f"{where} refuses — that's a sed script, not a joke: {content[:50]!r}")
        if is_opener and _words(content) > MULTITURN_OPENER_MAX:
            fails.append(f"multiturn opener is {_words(content)}w > {MULTITURN_OPENER_MAX}w — "
                         "the reply to small talk is brief or it isn't small talk")

    return [f"row {idx} [{cat}/{row.get('by')}] {f}" for f in fails]


def check_corpus(rows):
    """Corpus-level invariants — the ones no single row can violate alone.

    Mix and concentration checks only mean something once there's a corpus to
    measure. Below MIN_CORPUS this is the seed-authoring phase, where every
    category is legitimately thin and shouting about it just trains people to
    ignore the validator.
    """
    fails = []
    total = len(rows)
    MIN_CORPUS = 200

    if total < MIN_CORPUS:
        print(f"  (corpus checks skipped — {total} rows, need {MIN_CORPUS}; seed-authoring phase)")
        return fails

    by_cat = Counter(r["cat"] for r in rows)
    for cat in CATEGORIES:
        want = TARGET_MIX[cat] * total
        got = by_cat.get(cat, 0)
        if got < want * 0.5:
            fails.append(f"category {cat} is {got}/{want:.0f} — under half its target share")

    # Non-refusal share. A model that never lets anything through isn't funny.
    soft = by_cat.get("smalltalk", 0) + by_cat.get("distress", 0)
    if total and soft / total < 0.08:
        fails.append(f"only {soft/total:.0%} non-refusal rows — need >=8% or the model collapses to 'No.'")

    # Stock-line concentration. If one line is >6% of all targets, the model will
    # learn that line instead of learning the register.
    finals = [t[-1][1].strip().lower() for t in (r["turns"] for r in rows)]
    for line, n in Counter(finals).most_common(5):
        if total and n / total > 0.06:
            fails.append(f"line {line[:40]!r} is {n/total:.0%} of all targets — collapse risk")

    return fails


# ─────────────────────────────────────────────────────────────────────────────

def load_amplified():
    if not os.path.exists(AMPLIFIED):
        return []
    rows = []
    with open(AMPLIFIED) as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def to_chatml(row):
    msgs = [{"role": "system", "content": SYSTEM}]
    for role, content in row["turns"]:
        msgs.append({"role": role, "content": content})
    return {"messages": msgs,
            "meta": {"cat": row["cat"], "why": row["why"], "by": row["by"]}}


def main():
    rows = list(SEEDS) + load_amplified()
    print(f"{len(SEEDS)} seeds + {len(rows) - len(SEEDS)} amplified = {len(rows)} rows")

    fails = []
    for i, row in enumerate(rows):
        fails.extend(check_row(row, i))
    fails.extend(check_corpus(rows))

    if fails:
        print(f"\n{len(fails)} INVARIANT FAILURES\n" + "-" * 60)
        for f in fails:
            print(" ", f)
        print("\nNothing written. Fix the rows, not the validator.")
        return 1

    with open(OUT, "w") as f:
        for row in rows:
            f.write(json.dumps(to_chatml(row), ensure_ascii=False) + "\n")

    by_cat = Counter(r["cat"] for r in rows)
    by_who = Counter(r["by"] for r in rows)
    print(f"\nOK -> {OUT}")
    print("  " + ", ".join(f"{k}:{v}" for k, v in sorted(by_who.items())))
    print("  " + ", ".join(f"{c}:{by_cat.get(c,0)}" for c in CATEGORIES))
    return 0


if __name__ == "__main__":
    sys.exit(main())
